### ISSUE TITLE
Pre 0.1 checklist

### ISSUE THREAD

**Issue by floringogianu** [floringogianu/voy#5]
Some things we need before the first release:

**Must have**
- [x] switch to `uv` or a modern package manager, figure out the `pip` situation
- [ ] support for sql migrations
- [ ] mark recently updated authors so that we can limit the no of arxiv requests

**Nice to have**
- [ ] #1
- [x] full text search
